"""multiusuario: role en users y assignee en postulaciones

Revision ID: 42facff58357
Revises: a36def7ba43e
Create Date: 2026-06-23 15:53:14.374546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '42facff58357'
down_revision: Union[str, Sequence[str], None] = 'a36def7ba43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postulaciones', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'postulaciones', 'users', ['assignee_id'], ['id'])
    # El tipo enum no se crea solo con add_column; se crea explícito primero.
    userrole = postgresql.ENUM('ADMIN', 'MIEMBRO', name='userrole')
    userrole.create(op.get_bind(), checkfirst=True)
    # Los usuarios existentes son dueños de su empresa -> ADMIN (server_default).
    op.add_column(
        'users',
        sa.Column('role', postgresql.ENUM('ADMIN', 'MIEMBRO', name='userrole', create_type=False),
                  nullable=False, server_default='ADMIN'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(None, 'postulaciones', type_='foreignkey')
    op.drop_column('postulaciones', 'assignee_id')
    # ### end Alembic commands ###
