"""agrega departamento a search_profiles

Revision ID: 6d2dae18f9b4
Revises: 78f372d76af2
Create Date: 2026-06-22 21:01:58.065981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2dae18f9b4'
down_revision: Union[str, Sequence[str], None] = '78f372d76af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_profiles', sa.Column('departamento', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_profiles', 'departamento')
    # ### end Alembic commands ###
