"""esquema inicial: companies, users, search_profiles, opportunities, postulaciones

Revision ID: 78f372d76af2
Revises: 
Create Date: 2026-06-22 19:00:10.882973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f372d76af2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('plan', sa.Enum('GRATIS', 'ESENCIAL', 'PRO', 'AGENCIA', name='plan'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secop_id', sa.String(length=120), nullable=False),
    sa.Column('entidad', sa.String(length=300), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('departamento', sa.String(length=120), nullable=True),
    sa.Column('estado_secop', sa.String(length=120), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_ciudad'), 'opportunities', ['ciudad'], unique=False)
    op.create_index(op.f('ix_opportunities_secop_id'), 'opportunities', ['secop_id'], unique=True)
    op.create_table('postulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('NUEVA', 'REVISANDO', 'POSTULADA', 'GANADA', 'DESCARTADA', name='estadopostulacion'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'opportunity_id', name='uq_company_opportunity')
    )
    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('presupuesto_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('presupuesto_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('search_profiles')
    op.drop_table('postulaciones')
    op.drop_index(op.f('ix_opportunities_secop_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_ciudad'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('companies')
    # En PostgreSQL drop_table no elimina los tipos ENUM; se borran a mano
    # para que un re-upgrade no falle con "type already exists".
    bind = op.get_bind()
    sa.Enum(name='estadopostulacion').drop(bind, checkfirst=True)
    sa.Enum(name='plan').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
