"""agrega exclude_keywords a search_profiles

Revision ID: a36def7ba43e
Revises: 8a897ef27635
Create Date: 2026-06-23 12:22:01.676156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36def7ba43e'
down_revision: Union[str, Sequence[str], None] = '8a897ef27635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default '[]' para poblar las filas existentes; las nuevas usan el
    # default del modelo (list).
    op.add_column(
        'search_profiles',
        sa.Column('exclude_keywords', sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_profiles', 'exclude_keywords')
    # ### end Alembic commands ###
