"""agrega modalidad y tipo_contrato a opportunities

Revision ID: f50e314707b5
Revises: 6d2dae18f9b4
Create Date: 2026-06-22 21:20:59.772318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50e314707b5'
down_revision: Union[str, Sequence[str], None] = '6d2dae18f9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('modalidad', sa.String(length=200), nullable=True))
    op.add_column('opportunities', sa.Column('tipo_contrato', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'tipo_contrato')
    op.drop_column('opportunities', 'modalidad')
    # ### end Alembic commands ###
